import type {
  Property,
  DealAnalysis,
  Tenant,
  MaintenanceRequest,
  AgentLog,
  PortfolioSnapshot,
  Transaction,
} from "@/lib/types/database";

export const MOCK_PROPERTIES: Property[] = [
  {
    id: "prop-001",
    address: "14203 Desert Willow Dr",
    city: "Victorville",
    state: "CA",
    zip: "92392",
    type: "sfr",
    status: "pending_approval",
    list_price: 389000,
    purchase_price: 375000,
    current_value: null,
    mortgage_balance: null,
    monthly_rent: 2400,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1650,
    year_built: 2004,
    lot_size: 7200,
    zillow_id: "mock-001",
    zillow_url: "https://zillow.com",
    image_url: null,
    rejection_notes: null,
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prop-002",
    address: "2847 E Highland Ave",
    city: "San Bernardino",
    state: "CA",
    zip: "92404",
    type: "sfr",
    status: "underwriting",
    list_price: 325000,
    purchase_price: null,
    current_value: null,
    mortgage_balance: null,
    monthly_rent: 2200,
    bedrooms: 4,
    bathrooms: 2,
    sqft: 1820,
    year_built: 1987,
    lot_size: 6500,
    zillow_id: "mock-002",
    zillow_url: "https://zillow.com",
    image_url: null,
    rejection_notes: null,
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prop-003",
    address: "4512 Copper Hill Rd",
    city: "Apple Valley",
    state: "CA",
    zip: "92307",
    type: "sfr",
    status: "owned",
    list_price: 279000,
    purchase_price: 265000,
    current_value: 310000,
    mortgage_balance: 198000,
    monthly_rent: 1950,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1480,
    year_built: 1999,
    lot_size: 5800,
    zillow_id: "mock-003",
    zillow_url: "https://zillow.com",
    image_url: null,
    rejection_notes: null,
    created_at: new Date(Date.now() - 86400000 * 180).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prop-004",
    address: "891 W Foothill Blvd",
    city: "Rialto",
    state: "CA",
    zip: "92376",
    type: "duplex",
    status: "approved",
    list_price: 445000,
    purchase_price: 430000,
    current_value: null,
    mortgage_balance: null,
    monthly_rent: 3200,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2100,
    year_built: 2008,
    lot_size: 8000,
    zillow_id: "mock-004",
    zillow_url: "https://zillow.com",
    image_url: null,
    rejection_notes: null,
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prop-005",
    address: "11842 Oak Valley Pkwy",
    city: "Victorville",
    state: "CA",
    zip: "92392",
    type: "sfr",
    status: "dead",
    list_price: 410000,
    purchase_price: null,
    current_value: null,
    mortgage_balance: null,
    monthly_rent: 2100,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1600,
    year_built: 1995,
    lot_size: 7000,
    zillow_id: "mock-dead",
    zillow_url: "https://zillow.com",
    image_url: null,
    rejection_notes: "Cap rate below threshold",
    created_at: new Date(Date.now() - 86400000 * 14).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_DEAL_ANALYSES: DealAnalysis[] = [
  {
    id: "analysis-001",
    property_id: "prop-001",
    purchase_price: 375000,
    down_payment: 75000,
    down_payment_pct: 0.2,
    loan_amount: 300000,
    interest_rate: 0.07,
    loan_term: 30,
    monthly_mortgage: 1996,
    gross_monthly_rent: 2400,
    vacancy_rate: 0.05,
    effective_gross_income: 2280,
    operating_expenses: 798,
    noi_monthly: 1482,
    noi_annual: 17784,
    monthly_cash_flow: -514,
    annual_cash_flow: -6168,
    cap_rate: 0.0474,
    cash_on_cash_return: -0.065,
    dscr: 0.74,
    grm: 13.02,
    rehab_estimate: 15000,
    total_cash_needed: 98250,
    deal_score: 82,
    score_breakdown: { location: 8, cashflow: 7, appreciation: 9, condition: 8, financing: 8 },
    ai_summary:
      "Strong Victorville SFR in established neighborhood. Below-market purchase opportunity with value-add potential through rent optimization. High Desert market showing 6.2% YoY appreciation.",
    ai_recommendation: "buy",
    comparable_sales: [
      { address: "14100 Desert Willow Dr", sold_price: 382000, sold_date: "2025-11-15", sqft: 1620, beds: 3, baths: 2 },
      { address: "14350 Mojave Dr", sold_price: 395000, sold_date: "2025-10-22", sqft: 1700, beds: 3, baths: 2 },
      { address: "13980 Bear Valley Rd", sold_price: 368000, sold_date: "2025-09-08", sqft: 1580, beds: 3, baths: 2 },
    ],
    market_data: {
      avg_days_on_market: 28,
      list_to_sale_ratio: 0.97,
      avg_rent_by_bedroom: { "3": 2350 },
      vacancy_rate: 0.04,
      price_appreciation_12mo: 0.062,
      neighborhood_score: 72,
      population_growth: 0.018,
      job_growth: 0.024,
    },
    rehab_breakdown: {
      total_estimate: 15000,
      breakdown: { paint: 3000, flooring: 4000, kitchen: 5000, bathrooms: 2000, landscaping: 1000 },
      condition_rating: "good",
      value_add_potential: 25000,
    },
    created_at: new Date().toISOString(),
  },
];

export const MOCK_TENANTS: Tenant[] = [
  {
    id: "tenant-001",
    property_id: "prop-003",
    unit: "Main",
    first_name: "Maria",
    last_name: "Garcia",
    email: "maria.g@email.com",
    phone: "760-555-0201",
    monthly_rent: 1950,
    lease_start: "2024-06-01",
    lease_end: "2025-05-31",
    status: "active",
    screening_score: 88,
    screening_report: { credit: 720, income_ratio: 0.28 },
    created_at: new Date().toISOString(),
  },
];

export const MOCK_MAINTENANCE: MaintenanceRequest[] = [
  {
    id: "maint-001",
    property_id: "prop-003",
    tenant_id: "tenant-001",
    unit: "Main",
    title: "AC not cooling",
    description: "Air conditioner running but not producing cold air. Started yesterday.",
    priority: "high",
    status: "assigned",
    contractor_id: null,
    estimated_cost: 350,
    actual_cost: null,
    ai_diagnosis: "Likely refrigerant leak or compressor issue. HVAC service required.",
    ai_contractor_recommendation: "High Desert HVAC — 4.9 rating, avg 3hr response",
    submitted_at: new Date(Date.now() - 86400000).toISOString(),
    completed_at: null,
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "maint-002",
    property_id: "prop-003",
    tenant_id: "tenant-001",
    unit: "Main",
    title: "Dripping faucet",
    description: "Kitchen faucet dripping constantly.",
    priority: "low",
    status: "open",
    contractor_id: null,
    estimated_cost: 150,
    actual_cost: null,
    ai_diagnosis: "Standard faucet cartridge replacement.",
    ai_contractor_recommendation: "Desert Pro Plumbing",
    submitted_at: new Date().toISOString(),
    completed_at: null,
    created_at: new Date().toISOString(),
  },
];

export const MOCK_AGENT_LOGS: AgentLog[] = [
  { id: "log-1", agent: "deal_scanner", action: "scan_completed", property_id: null, input: { listings_found: 12 }, output: { qualified: 3 }, tokens_used: 2400, status: "success", created_at: new Date(Date.now() - 3600000).toISOString() },
  { id: "log-2", agent: "underwriter", action: "analysis_complete", property_id: "prop-001", input: null, output: { score: 82 }, tokens_used: 1800, status: "success", created_at: new Date(Date.now() - 7200000).toISOString() },
  { id: "log-3", agent: "refi_monitor", action: "heloc_eligible", property_id: "prop-003", input: null, output: { equity_pct: 0.36 }, tokens_used: 0, status: "success", created_at: new Date(Date.now() - 86400000).toISOString() },
  { id: "log-4", agent: "maintenance_router", action: "request_routed", property_id: "prop-003", input: { priority: "high" }, output: { contractor: "High Desert HVAC" }, tokens_used: 450, status: "success", created_at: new Date(Date.now() - 86400000).toISOString() },
  { id: "log-5", agent: "financial_reporter", action: "monthly_report", property_id: null, input: null, output: { anomalies: 0 }, tokens_used: 620, status: "success", created_at: new Date(Date.now() - 86400000 * 3).toISOString() },
];

export const MOCK_SNAPSHOTS: PortfolioSnapshot[] = Array.from({ length: 12 }, (_, i) => {
  const month = 11 - i;
  const year = month >= 0 ? 2025 : 2024;
  const m = month >= 0 ? month + 1 : month + 13;
  return {
    id: `snap-${i}`,
    snapshot_date: `${year}-${String(m).padStart(2, "0")}-01`,
    total_properties: i < 6 ? 1 : 1,
    total_portfolio_value: 265000 + i * 4500,
    total_debt: 210000 - i * 1200,
    total_equity: 55000 + i * 5700,
    gross_monthly_rent: 1950,
    total_monthly_expenses: 1420,
    net_monthly_cash_flow: 530 + i * 15,
    overall_coc_return: 0.068 + i * 0.002,
    created_at: new Date().toISOString(),
  };
});

export const MOCK_TRANSACTIONS: Transaction[] = [
  { id: "tx-1", property_id: "prop-003", type: "income", category: "rent", amount: 1950, description: "March rent", date: "2026-03-01", tenant_id: "tenant-001", contractor_id: null, created_at: new Date().toISOString() },
  { id: "tx-2", property_id: "prop-003", type: "expense", category: "mortgage", amount: 1420, description: "P&I payment", date: "2026-03-01", tenant_id: null, contractor_id: null, created_at: new Date().toISOString() },
  { id: "tx-3", property_id: "prop-003", type: "expense", category: "insurance", amount: 145, description: "Landlord insurance", date: "2026-03-05", tenant_id: null, contractor_id: null, created_at: new Date().toISOString() },
];

export const PORTFOLIO_KPIS = {
  totalProperties: 1,
  totalPortfolioValue: 310000,
  totalEquity: 112000,
  netMonthlyCashFlow: 530,
  overallCoCReturn: 0.082,
  liquidCapital: 85000,
};

export const CASH_FLOW_CHART = MOCK_SNAPSHOTS.map((s) => ({
  month: new Date(s.snapshot_date).toLocaleDateString("en-US", { month: "short" }),
  cashFlow: s.net_monthly_cash_flow ?? 0,
}));

export const EQUITY_CHART = MOCK_SNAPSHOTS.map((s) => ({
  month: new Date(s.snapshot_date).toLocaleDateString("en-US", { month: "short" }),
  equity: s.total_equity ?? 0,
  debt: s.total_debt ?? 0,
}));

export const INCOME_EXPENSE_CHART = [
  { category: "Rent", amount: 1950 },
  { category: "Mortgage", amount: -1420 },
  { category: "Insurance", amount: -145 },
  { category: "Maintenance", amount: -85 },
  { category: "Taxes", amount: -210 },
  { category: "Management", amount: -0 },
];
