-- Deal Scanner Phase 1 — extended deals columns
-- Safe for databases that never ran migration 003/004 fully

-- Core columns (if table was created manually)
ALTER TABLE deals ADD COLUMN IF NOT EXISTS property_id UUID;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS property_type TEXT;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS list_price NUMERIC;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS coc_return NUMERIC;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS ai_score NUMERIC;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();

-- Migration 004 fields
ALTER TABLE deals ADD COLUMN IF NOT EXISTS adu_rent_estimate NUMERIC DEFAULT 0;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS mortgage_estimate NUMERIC DEFAULT 0;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS adu_coverage_pct NUMERIC DEFAULT 0;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS market TEXT DEFAULT '';
ALTER TABLE deals ADD COLUMN IF NOT EXISTS condition TEXT DEFAULT 'cosmetic';
ALTER TABLE deals ADD COLUMN IF NOT EXISTS commute_min INTEGER DEFAULT 0;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS phase2_coc NUMERIC DEFAULT 0;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS fha_eligible BOOLEAN DEFAULT true;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS city TEXT DEFAULT '';
ALTER TABLE deals ADD COLUMN IF NOT EXISTS notes TEXT DEFAULT '';

-- Deal Scanner fields
ALTER TABLE deals ADD COLUMN IF NOT EXISTS bedrooms INTEGER;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS bathrooms NUMERIC;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS sqft INTEGER;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS lot_size NUMERIC;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS adu_exists BOOLEAN DEFAULT false;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS monthly_mortgage NUMERIC;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS monthly_rental_income NUMERIC;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS monthly_cash_flow NUMERIC;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS rent_coverage_ratio NUMERIC;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS total_cash_needed NUMERIC;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS listing_url TEXT;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'new';

CREATE INDEX IF NOT EXISTS idx_deals_ai_score ON deals(ai_score DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS idx_deals_status ON deals(status);
CREATE INDEX IF NOT EXISTS idx_deals_market ON deals(market);
